# -----------------------------
# Application Service
# - NodePort so you can reach it like hostIP:30090 (maps to container 8080)
# - Service "port" is 9090 to mirror your compose mapping.
# -----------------------------

# -----------------------------
# Application Deployment
# -----------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  namespace: spring-mysql
  labels:
    app: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
        - name: spring-app
          image: dkr.ecr.ap-south-1.amazonaws.com/dev-marketing:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: application-svc
  namespace: spring-mysql
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app: application
  ports:
    - port: 80
      targetPort: 8080
---
# -----------------------------
# Horizontal Pod Autoscaler (HPA) for the application
# Requires metrics-server installed
# -----------------------------
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: application-hpa
  namespace: spring-mysql
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: application
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20

---
